default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>

development:
  <<: *default
  database: internal_wallet_transaction_system_api

test:
  <<: *default
  database: internal_wallet_transaction_system_api_test

production:
  primary: &primary_production
    <<: *default
    database: internal_wallet_transaction_system_api_production
    username: internal_wallet_transaction_system_api
    password: <%= ENV["INTERNAL_WALLET_TRANSACTION_SYSTEM_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: internal_wallet_transaction_system_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: internal_wallet_transaction_system_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: internal_wallet_transaction_system_api_production_cable
    migrations_paths: db/cable_migrate